### ISSUE TITLE
submenu RTL issue

### ISSUE THREAD

**Issue by hosseinfarnia** [Nikeo/customizr#1421]
Hi @Nikeo 
multiple Submenus on desktop devices are not aligned to right in RTL languages.
I have provided a screencast for better understanding in the following:
this is the current position in customizr theme which is wrong:
https://screencast-o-matic.com/watch/cFVulyouSP
and this one is the correct position in another theme (Hestia):
https://screencast-o-matic.com/watch/cFVuluouS8
Thank you very much for your attention

**Comment by hosseinfarnia** [comment]
Hi,
I realized that it has been fixed already.
Sorry for opening this issue.
Thank you

**Comment by eri-trabiccolo** [comment]
Hi @hosseinfarnia ,
actually this issue is still valid for the modern style and is not fixed yet. Thanks for reporting this.
This other fixed issue https://github.com/presscustomizr/customizr/issues/1414 refers to the background animation on hover for submenu items.

Best.

**Comment by eri-trabiccolo** [comment]
fixed in
#1429 
https://github.com/presscustomizr/customizr-front-js-parts/pull/34

**Comment by ghost** [comment]
Hi @hosseinfarnia thank you very much for reporting this problem. And for the screecasts, it helped !
@eri-trabiccolo thanks for the PR
